IDE:
  - "nvim"
  - "code"

# Optional. Default: true
overrideFormatter: true

# Optional. Default: true
addToGitIgnore: true

# Optional. Default: 3
depth: 3

# Optional. Default: 2
logLvl: 2
# Optional. Default: "~/.config/autoFormatter/logs"
logPath: "~/.config/autoFormatter/logs"

# Optional. Default: [".git", "build", "target"]
exludeFolders:
  - ".git"
  - "build"
  - "target"

formatters:
  - cpp:
      formatter: ".clang-format"
      filetypes:
        - ".cpp"
        - ".hpp"
        - ".h"
  - c:
      formatter: ".clang-format"
      filetypes:
        - ".c"
        - ".h"
  - rust:
      formatter: ".rustfmt.toml"
      filetypes:
        - ".rs"
  - odin:
      formatter: "odinfmt.json"
      filetypes:
        - ".odin"
  - Csharp:
      formatter: ".editorconfig"
      filetypes:
        - ".cs"
