IDE:
  - "nvim"
  - "code"

formatters:
  - cpp:
      formatter: ".clang-formatter"
      filetypes:
        - ".cpp"
        - ".hpp"
        - ".h"
  - c:
      formatter: ".clang-formatter"
      filetypes:
        - ".c"
        - ".h"
  - rust:
      formatter: ".rustfmt.toml"
      filetypes:
        - ".rs"
  - odin:
      formatter: "odinfmt.json"
      filetypes:
        - ".odin"
  - Csharp:
      formatter: ".editorconfig"
      filetypes:
        - ".cs"
